service: service-processor-serverless
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  stage: dev
  region: us-east-1
  environment:
    API_GT_ID: !Sub ${ApiGatewayRestApi}
    SQS_URL: ${construct:anonymizer.queueUrl}
    USERS_TABLE: ${self:provider.stage}-user

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: '*'

constructs:
  anonymizer:
    type: queue
    worker:
      handler: src/processor.anonymizer

functions:
  create:
    handler: src/api.create
    events:
      - http:
          method: post
          path: create
    environment:
      QUEUE_URL: ${construct:anonymizer.queueUrl}

resources:
  Resources:
    UserDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USERS_TABLE}

plugins:
  - serverless-lift
  - serverless-bundle
